#==============================================================================
# Crate config
[package]
name = "soh_libs"
version = "0.1.0"
edition = "2021"

[dependencies]
soh_rng = { path = "./soh_rng", optional = true }
soh_log = { path = "./soh_log", optional = true }
soh_vk  = { path = "./soh_vk",  optional = true }

[features]
default = [ ]
rng = [ "dep:soh_rng" ]
log = [ "dep:soh_log" ]
vk  = [ "dep:soh_vk" ]

#==============================================================================
# Workspace config
[workspace]
members = [
    "soh_rng",
    "soh_log",
    "soh_vk"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = ">=1.0,<2.0"
clap = { version = ">=4.0,<5.0", features = [ "derive" ] }
ash = { version = "0.38", features = [ "linked" ] }
sdl2 = "0.37"

[workspace.lints.clippy]
needless_return = "allow"

#==============================================================================
