[package]
name = "soh_vk"
version.workspace = true
edition.workspace = true

[dependencies]
ash = { workspace = true }
sdl2 = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
